# Configuration File BankPlus
#
# Made by Pulsi_

Update-Checker: true

Interest:
  # Interest will give players that has money in bank
  # a % of the amount every <num> of minutes etc..
  Enabled: true
  Money-Given: "5" # 5% of the bank amount
  Delay: "5" #5 Minutes
  Max-Amount: 500000

General:

  Join-Start-Amount: 500

  # Will use players UUIDs for store moneys,
  # otherwise, it will use players Names
  Use-UUID: true

  Withdraw-Sound:
    Enabled: true
    Sound: "ENTITY_PLAYER_LEVEL_UP,5,1" #Sound Type, Volume, Pitch
  Deposit-Sound:
    Enabled: true
    Sound: "ENTITY_ORB_PICKUP,5,1"
  View-Sound:
    Enabled: true
    Sound: "ENTITY_ORB_PICKUP,5,1"
  Personal-Sound:
    Enabled: true
    Sound: "ENTITY_ORB_PICKUP,5,1"

Placeholders:
  Money:
    Thousands: "K"
    Millions: "M"
    Billions: "B"
    Trillions: "T"
    Quadrillions: "Q"
  Time:
    Minute: " Minute"
    Minutes: " Minutes"
    Hour: " Hour"
    Hours: " Hours"
    Day: " Day"
    Days: " Days"

Gui:
  #
  # If the GUI its enabled, typing /bank
  # won't display the amount of Money
  # but will open this GUI
  #
  # The gui now supports Placeholders!
  #
  # In case you don't have PlaceholderAPI installed
  # You can use Local placeholders:
  # %player_name% -> Return the player name
  # %balance% -> Return player balance
  # %balance_formatted% -> Return player balance formatted
  # %balance_formatted_long% -> Return player balance formatted without "."
  # %interest_cooldown% -> Return the interest cooldown
  #
  Enabled: true
  Title: "&a&lGui Bank"
  Lines: 3
  Update-Delay: 1 #In seconds, put 0 to disable
  Filler:
    Enabled: true
    Material: "WHITE_STAINED_GLASS_PANE"
    DisplayName: "&6"
    Glowing: false
  Items:
    # You can add as many items as you want
    # and not only for make the bank work
    Withdraw:
      Material: "EMERALD"
      DisplayName: "&aWithdraw"
      Slot: 11
      Lore:
        - ""
        - "&7Withdraw &a500$ &7from your bank"
        - ""
      Glowing: true
      Action:
        # You can choose a number or:
        # "ALL" -> All money
        # "HALF" -> Half of the money
        Action-Type: "Withdraw"
        Amount: "500"

    WithdrawHalf:
      Material: "EMERALD"
      DisplayName: "&aWithdraw"
      Slot: 12
      Lore:
        - ""
        - "&7Withdraw &aHalf &7of the money from your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Withdraw"
        Amount: "HALF"

    WithdrawAll:
      Material: "EMERALD"
      DisplayName: "&aWithdraw"
      Slot: 21
      Lore:
        - ""
        - "&7Withdraw &aAll &7of the money from your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Withdraw"
        Amount: "ALL"
    WithdrawCustom:
      Material: "EMERALD"
      Slot: 20
      DisplayName: "&aWithdraw"
      Lore:
        - ""
        - "&7Withdraw a &acustom &7amount of your money to your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Withdraw"
        Amount: "CUSTOM"

    Personal-Info:
      Material: "PAPER"
      DisplayName: "&aPersonal"
      Slot: 14
      Lore:
        - ""
        - "&7Account Name: &f%player_name%"
        - "&7Balance: &a%bankplus_balance_formatted%"
        - ""
        - "&7Wait more &a%bankplus_interest_cooldown% &7to get interest!"
        - ""
      Glowing: true

    Deposit:
      Material: "EMERALD"
      Slot: 17
      DisplayName: "&aDeposit"
      Lore:
        - ""
        - "&7Deposit &a500$ &7to your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Deposit"
        Amount: "500"

    DepositHalf:
      Material: "EMERALD"
      Slot: 16
      DisplayName: "&aDeposit"
      Lore:
        - ""
        - "&7Deposit &aHalf &7of your money to your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Deposit"
        Amount: "HALF"

    DepositAll:
      Material: "EMERALD"
      Slot: 25
      DisplayName: "&aDeposit"
      Lore:
        - ""
        - "&7Deposit &aAll &7of your money to your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Deposit"
        Amount: "ALL"

    DepositCustom:
      Material: "EMERALD"
      Slot: 26
      DisplayName: "&aDeposit"
      Lore:
        - ""
        - "&7Deposit a &acustom &7amount of your money to your bank"
        - ""
      Glowing: true
      Action:
        Action-Type: "Deposit"
        Amount: "CUSTOM"