# Configuration File of BankPlus
# Made by Pulsi_, Version v5.2

# Check for new updates of the plugin.
Update-Checker: true

# Interest will give players that has money in
# their bank a % of the amount every x minutes.
#
# To restart the interest type /bank restartInterest.
Interest:
  # Enable or disable the interest feature.
  Enabled: true

  AFK-Settings:
    # If a player is AFK, it won't receive the interest.
    Ignore-AFK-Players: true

    # The time, in minutes, that will pass
    # before marking a player as AFK
    AFK-Time: 5

  # ( it will add: balance x Money-Given )
  Money-Given: 0.02

  # This is the interest cooldown.
  # You can choose the delay between:
  #   seconds (time s), minutes (time m)
  #   hours (time h), days (time d)
  # If no time will be specified, it will
  # automatically choose the minutes.
  Delay: 1 h

  # The max amount that you can receive with interest.
  Max-Amount: 5000

  # Choose if also giving interest to offline players.
  Give-To-Offline-Players: false

General:
  # The amount that a player will receive
  # when joining for the first time
  Join-Start-Amount: 500

  # Store player's money using UUIDs,
  # otherwise the plugin will use names.
  Use-UUIDs: true

  # The max amount that a player can deposit, use 0 to disable.
  Max-Bank-Capacity: 500000000

  # The max amount of decimals that a player balance can have.
  Max-Decimals-Amount: 2

  # The max amount to withdraw per time, use 0 to disable.
  Max-Withdrawn-Amount: 0

  # The max amount to deposit per time, use 0 to disable.
  Max-Deposit-Amount: 0

  # The minimum amount that a player needs to
  # put to withdraw / deposit, put 0 to disable.
  Minimum-Amount: 0

  # Enabling this option, it will reopen the bank after
  # typing in chat when depositing / withdraw money.
  Reopen-Bank-After-Chat: true

  # The message that a player has to type
  # to stop typing the custom amount.
  Chat-Exit-Message: exit

  # These commands will be executed when leaving from typing
  # in chat while using the custom withdraw / deposit.
  # You can put as many commands as you want.
  Chat-Exit-Commands: '[]'
  # - "[CONSOLE] tell %player% You closed the bank!"
  # - "[PLAYER] say I closed the bank!"

  # Worlds where the bank won't work
  Worlds-Blacklist: true

  # Send an alert message to show the player how
  # much money has earned while being offline.
  Offline-Interest-Earned-Message:
    Enabled: false
    # In seconds, put 0 to disable the delay.
    Delay: 2
    Message: '&a&lBank&9&lPlus &aYou have earned &f%amount% money &awhile being offline!'

  Withdraw-Sound:
    Enabled: true
    # Sound-Type,Volume,Pitch.
    Sound: ENTITY_EXPERIENCE_ORB_PICKUP,5,1

  Deposit-Sound:
    Enabled: true
    Sound: ENTITY_EXPERIENCE_ORB_PICKUP,5,1

  View-Sound:
    Enabled: true
    Sound: ENTITY_EXPERIENCE_ORB_PICKUP,5,1

  Personal-Sound:
    Enabled: true
    Sound: ENTITY_EXPERIENCE_ORB_PICKUP,5,1

Placeholders:
  Money:
    Thousands: K
    Millions: M
    Billions: B
    Trillions: T
    Quadrillions: Q
    Quintillions: QQ

  Time:
    Second: Second
    Seconds: Seconds
    Minute: Minute
    Minutes: Minutes
    Hour: Hours
    Day: Days
    Days: Days
    Interest-Time:
      Only-Seconds: '%seconds% %seconds_placeholder%'
      Only-Minutes: '%minutes% %minutes_placeholder%'
      Only-Hours: '%hours% %hours_placeholder%'
      Only-Days: '%days% %days_placeholder%'
      Seconds-Minutes: '%seconds% %seconds_placeholder% and %minutes% %minutes_placeholder%'
      Seconds-Hours: '%seconds% %seconds_placeholder% and %hours% %hours_placeholder%'
      Seconds-Days: '%seconds% %seconds_placeholder% and %days% %days_placeholder%'
      Seconds-Minutes-Hours: '%seconds% %seconds_placeholder%, %minutes% %minutes_placeholder%
        and %hours% %hours_placeholder%'
      Seconds-Hours-Days: '%seconds% %seconds_placeholder%, %hours% %hours_placeholder%
        and %days% %days_placeholder%'
      Seconds-Minutes-Days: '%seconds% %seconds_placeholder%, %minutes% %minutes_placeholder%
        and %days% %days_placeholder%'
      Seconds-Minutes-Hours-Days: '%seconds% %seconds_placeholder%, %minutes% %minutes_placeholder%,
        %hours% %hours_placeholder% and %days% %days_placeholder%'
      Minutes-Hours: '%minutes% %minutes_placeholder% and %hours% %hours_placeholder%'
      Minutes-Days: '%minutes% %minutes_placeholder% and %days% %days_placeholder%'
      Minutes-Hours-Days: '%minutes% %minutes_placeholder%, %hours% %hours_placeholder%
        and %days% %days_placeholder%'
      Hours-Days: '%hours% %hours_placeholder% and %days% %days_placeholder%'