name: BankPlus
version: 4.2
main: me.pulsi_.bankplus.BankPlus
api-version: 1.13
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - EssentialsX
  - EconomyPlus
authors: [ Pulsi_ ]
load: POSTWORLD
description: The best bank plugin of Spigot!
commands:
  bankplus:
    aliases: [bankp, bank, bp]